services:
  tanks:
    build: .
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/var/opt/tanks/dist/data
      # - type: bind
      #   source: server-preferences.json
      #   target: /var/opt/tanks/dist/server-preferences.json